run tests in docker imagee

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -16,54 +16,34 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
+      - name: Build and test Docker image
+        run: |
+          docker build -t $DOCKER_IMAGE_NAME .
+          docker run $DOCKER_IMAGE_NAME npm test > test-results.txt
+
+      - name: Check test status
+        id: check-tests
+        run: |
+          test_results=$(cat test-results.txt)
+          if [[ $test_results == *"FAIL"* ]]; then
+            echo "Tests failed. Aborting deployment."
+            exit 1
+          else
+            echo "Tests passed. Proceeding with deployment."
+          fi
+
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v2
-        with:
-          context: ./client
-          file: ./client/DockerFile.prod
-          push: true
-          tags: ${{ env.DOCKER_IMAGE_NAME }}
-          build-args: REACT_APP_TMDB_KEY=${{ secrets.REACT_APP_TMDB_KEY }}
-
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Pull Docker image from Docker Hub
-        run: docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest
-
-      - name: Tag Docker image for GitHub Packages
-        run: docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest
-
-      - name: Push Docker image to GitHub Packages
-        run: docker push ghcr.io/${{ github.repository }}/${{ env.DOCKER_IMAGE_NAME }}:latest
-
-      - name: Create Docker container
-        run: docker create --name react_app_container ${{ env.DOCKER_IMAGE_NAME }}:latest
-
-      - name: Copy built React app from Docker container
-        run: docker cp react_app_container:/usr/share/nginx/html ./build
-
-      - name: Remove Docker container
-        run: docker rm react_app_container
-
-      - name: Deploy coverage report to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v3
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./coverage/lcov-report
+      - name: Push Docker image
+        run: docker push $DOCKER_IMAGE_NAME
 
       - name: Deploy to GitHub Pages
+        if: ${{ steps.check-tests.outcome == 'success' }}
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./build
+          publish_dir: ./client/build
